import { useState } from 'react';
import { Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createCivicIssue, getCivicIssues, getCivicProjects } from '@/services/api';
import { Badge, Button, Card, Empty, Field, Loading, Muted, Screen, SectionHeader, Title } from '@/components/UI';
import { useTheme } from '@/features/theme/ThemeProvider';
import { useBreakpoint } from '@/hooks/useBreakpoint';
import { formatMoney } from '@/utils/format';

export default function GovernanceScreen(){
 const {theme}=useTheme(); const {isPhone}=useBreakpoint(); const qc=useQueryClient(); const projects=useQuery({queryKey:['civic-projects'],queryFn:getCivicProjects}); const issues=useQuery({queryKey:['civic-issues'],queryFn:getCivicIssues});
 const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [location,setLocation]=useState('');
 const submit=useMutation({mutationFn:()=>createCivicIssue({title,description,category:'public-service',location_text:location}),onSuccess:()=>{setTitle('');setDescription('');setLocation('');qc.invalidateQueries({queryKey:['civic-issues']});}});
 const totalBudget=(projects.data||[]).reduce((s,p)=>s+(p.budget||0),0); const totalSpent=(projects.data||[]).reduce((s,p)=>s+(p.spent||0),0);
 return <Screen><View style={{width:'100%',maxWidth:1200,alignSelf:'center',gap:16}}><SectionHeader title="Civic Transparency Dashboard" subtitle="Public projects, financial allocations, citizen reports, and audit status" right={<Badge tone="success">Transparency Hub</Badge>}/>
  <View style={{flexDirection:isPhone?'column':'row',gap:12}}><Card style={{flex:1}}><Muted>Project budget</Muted><Title size={22}>{formatMoney(totalBudget)}</Title></Card><Card style={{flex:1}}><Muted>Recorded spending</Muted><Title size={22}>{formatMoney(totalSpent)}</Title></Card><Card style={{flex:1}}><Muted>Citizen reports</Muted><Title size={22}>{issues.data?.length||0}</Title></Card></View>
  <View style={{flexDirection:isPhone?'column':'row',gap:16,alignItems:'flex-start'}}><View style={{flex:2,width:'100%',gap:12}}><Title size={16}>Project Monitor</Title>{projects.isLoading?<Loading/>:projects.data?.length?projects.data.map(p=><Card key={p.id}><View style={{flexDirection:'row',justifyContent:'space-between',gap:10}}><View style={{flex:1}}><Text style={{color:theme.text,fontWeight:'900'}}>{p.title}</Text><Muted>{p.sector} · {p.location||'Public project'}</Muted></View><Badge tone={p.status==='completed'?'success':p.status==='delayed'?'danger':'info'}>{p.status}</Badge></View><Text style={{color:theme.textSecondary,fontSize:12,lineHeight:18,marginTop:10}}>{p.description}</Text><View style={{height:8,backgroundColor:theme.muted,borderRadius:999,marginTop:12,overflow:'hidden'}}><View style={{height:'100%',width:`${Math.min(100,Math.max(0,p.progress))}%`,backgroundColor:theme.info}}/></View><View style={{flexDirection:'row',justifyContent:'space-between',marginTop:6}}><Muted size={10}>{p.progress}% complete</Muted><Muted size={10}>{formatMoney(p.spent)} / {formatMoney(p.budget)}</Muted></View></Card>):<Empty title="No public projects" description="Run the optional public seed or add projects using an admin account."/>}</View>
  <View style={{flex:1,width:'100%',gap:12}}><Title size={16}>File Citizen Report</Title><Card style={{gap:10}}><Field placeholder="Issue title" value={title} onChangeText={setTitle}/><Field placeholder="Location / barangay" value={location} onChangeText={setLocation}/><Field multiline placeholder="Describe the issue and useful evidence…" value={description} onChangeText={setDescription} style={{minHeight:100,textAlignVertical:'top'}}/><Button variant="danger" disabled={!title.trim()||!description.trim()||submit.isPending} onPress={()=>submit.mutate()}>{submit.isPending?'Submitting…':'Submit report'}</Button><Muted size={10}>Reports are timestamped and tied to your authenticated account. Administrators can update status, but cannot impersonate the reporter.</Muted></Card><Title size={16}>Recent reports</Title>{(issues.data||[]).slice(0,6).map(i=><Card key={i.id}><View style={{flexDirection:'row',justifyContent:'space-between',gap:8}}><Text style={{color:theme.text,fontWeight:'800',flex:1}}>{i.title}</Text><Badge tone={i.status==='resolved'?'success':'warning'}>{i.status}</Badge></View><Muted>{i.location_text||i.category}</Muted></Card>)}</View></View>
 </View></Screen>;
}
