import { useState } from 'react';
import { Text, View } from 'react-native';
import { useMutation, useQuery } from '@tanstack/react-query';
import { applyToJob, getJobs } from '@/services/api';
import { Badge, Button, Card, Empty, Field, Loading, Muted, Screen, SectionHeader, Title } from '@/components/UI';
import { useBreakpoint } from '@/hooks/useBreakpoint';
import { useTheme } from '@/features/theme/ThemeProvider';

export default function JobsScreen(){const{isPhone}=useBreakpoint();const{theme}=useTheme();const jobs=useQuery({queryKey:['jobs'],queryFn:getJobs});const[note,setNote]=useState('Interested and available for interview.');const apply=useMutation({mutationFn:(id:string)=>applyToJob(id,note)});return <Screen><View style={{width:'100%',maxWidth:1100,alignSelf:'center',gap:14}}><SectionHeader title="Career Center" subtitle="Local jobs, civic employment, resume workflow, and application tracking"/><Card style={{gap:8}}><Title size={14}>Application note</Title><Field value={note} onChangeText={setNote} placeholder="Reusable note sent with an application"/><Muted size={10}>Applications are private to the applicant and the job owner/admin under RLS.</Muted></Card>{jobs.isLoading?<Loading/>:jobs.data?.length?<View style={{flexDirection:'row',flexWrap:'wrap',gap:12}}>{jobs.data.map(j=><Card key={j.id} style={{width:(isPhone?'100%':'48.8%') as any,minHeight:180}}><View style={{flexDirection:'row',justifyContent:'space-between',gap:8}}><View style={{flex:1}}><Title size={16}>{j.title}</Title><Muted>{j.company} · {j.location||'Philippines'}</Muted></View><Badge tone="success">{j.employment_type||'Open'}</Badge></View><Text style={{color:theme.textSecondary,fontSize:12,lineHeight:18,marginVertical:10,flex:1}}>{j.description}</Text><Button disabled={apply.isPending} onPress={()=>apply.mutate(j.id)}>{apply.isPending?'Applying…':'Apply'}</Button></Card>)}</View>:<Empty title="No open jobs" description="Job opportunities will appear here."/>}</View></Screen>;}
