import { useEffect, useState } from 'react';
import { Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getMyProfile, updateMyProfile } from '@/services/api';
import { Badge, Button, Card, Field, Loading, Muted, Screen, SectionHeader, Title } from '@/components/UI';
import { useTheme } from '@/features/theme/ThemeProvider';
import { useAuth } from '@/features/auth/AuthProvider';

export default function ProfileScreen(){const{theme}=useTheme();const{signOut}=useAuth();const qc=useQueryClient();const profile=useQuery({queryKey:['my-profile'],queryFn:getMyProfile});const[name,setName]=useState('');const[username,setUsername]=useState('');const[bio,setBio]=useState('');const[city,setCity]=useState('');const[barangay,setBarangay]=useState('');useEffect(()=>{if(profile.data){setName(profile.data.full_name||'');setUsername(profile.data.username||'');setBio(profile.data.bio||'');setCity(profile.data.city||'');setBarangay(profile.data.barangay||'');}},[profile.data]);const save=useMutation({mutationFn:()=>updateMyProfile({full_name:name,username,bio,city,barangay}),onSuccess:()=>qc.invalidateQueries({queryKey:['my-profile']})});if(profile.isLoading)return <Loading/>;return <Screen><View style={{width:'100%',maxWidth:760,alignSelf:'center',gap:14}}><SectionHeader title="My Civic Identity" subtitle="Identity, public profile, verification indicators, and civic reputation" right={profile.data?.is_verified?<Badge tone="success">Verified</Badge>:<Badge tone="neutral">Unverified</Badge>}/><Card style={{alignItems:'center',gap:8}}><View style={{width:80,height:80,borderRadius:40,backgroundColor:theme.muted,alignItems:'center',justifyContent:'center'}}><Text style={{color:theme.text,fontSize:28,fontWeight:'900'}}>{(profile.data?.full_name||'K').slice(0,1)}</Text></View><Title size={20}>{profile.data?.full_name||'Citizen'}</Title><Text style={{color:theme.info,fontWeight:'900'}}>Civic Score {profile.data?.civic_score??0}</Text></Card><Card style={{gap:10}}><Title size={15}>Edit profile</Title><Field placeholder="Full name" value={name} onChangeText={setName}/><Field autoCapitalize="none" placeholder="Username" value={username} onChangeText={setUsername}/><Field placeholder="City / municipality" value={city} onChangeText={setCity}/><Field placeholder="Barangay" value={barangay} onChangeText={setBarangay}/><Field multiline placeholder="Bio" value={bio} onChangeText={setBio} style={{minHeight:90,textAlignVertical:'top'}}/><Button disabled={!name.trim()||save.isPending} onPress={()=>save.mutate()}>{save.isPending?'Saving…':'Save profile'}</Button><Muted size={10}>Sensitive fields such as government ID numbers, home addresses, and health records are intentionally not part of the public profile schema.</Muted></Card><Button variant="danger" onPress={()=>signOut()}>Sign out</Button></View></Screen>;}
